### ISSUE TITLE
Interactive plots consume too much memory

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#1713]
To reproduce, run the following code fragment several times (e.g. 4):

```python
import plotly.express as px
import numpy as np

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])
fig.show()
```

The plots all show up in the pane:

<img width="672" alt="image" src="https://github.com/posit-dev/positron/assets/470418/77c787fb-25e4-4e5a-9a43-3570ebb2bb2c">

Note that Positron's memory usage goes up each time, and an entire separate process is started for each plot, since each one is a webview.

<img width="428" alt="image" src="https://github.com/posit-dev/positron/assets/470418/c093e0a3-4915-4c48-8ab2-1215769fd895">

We should cache the data needed to create the webview and its thumbnail and hibernate it following some heuristic (e.g. ensure that the number of plot webviews doesn't exceed some cap, and hibernate webviews that are older than a minute or two)

**Comment by seeM** [comment]
A bit of an effort to verify, here's what I did.

**There should be no more than 5 plot webviews:**

1. Create 5 webview plots and change their state somehow e.g. zoom in.
2. Create a 6th webview plot.
3. Select the first plot and confirm that its zoom level reset i.e. the webview was recreated.

**Webview plots should be disposed after 2 minutes:**

1. Create a webview plot and change its state e.g. zoom in.
2. Create another webview plot and change is state too.
3. Wait 2 minutes.
4. Select the first webview plot and confirm that its zoom level reset i.e. the webview was recreated.
5. Reselect the other webview plot - its zoom level should have been retained since it was recently shown.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-77
    OS Version          : OSX

### Test scenario(s) 

Verified with Wasim's instructions.

Link(s) to TestRail test cases run or created:
N/A
