### ISSUE TITLE
R: Add Run Line/Selection in Console to Toolbar menu, right click menu, command palette

### ISSUE THREAD

**Issue by jgutman** [posit-dev/positron#2084]
We've just made these changes on the Python side, and I think may want similar changes in the R extension. So we currently have the keyboard shortcut (Cmd+Enter) to run a line/selection of R code in the console, but there's no other way to access it. This is in contrast to sourcing an entire R file, for which we have a keyboard shortcut, and it can also be accessed in the following places:

this button
<img width="197" alt="image" src="https://github.com/posit-dev/positron/assets/7817881/88f60f7a-d54d-4c02-a30a-e5057eb1fc47">

this menu option (right click on file in editor)
<img width="265" alt="image" src="https://github.com/posit-dev/positron/assets/7817881/173d39b9-4a57-40cc-81ce-3822480a7e03">

command palette
<img width="628" alt="image" src="https://github.com/posit-dev/positron/assets/7817881/ff677d8e-c656-4560-b77c-f22ec4060442">

In #2068 for Python, we added "Run Line/Selection in Console" as an option in all these places. For the Run/Play icon in the toolbar, we made Run Line/Selection the first/default option, so if you just click on the play icon, by default it just runs selection, or you could click on the dropdown and choose to source the entire file (second option in the list, below Run Line/Selection)
![image](https://github.com/posit-dev/positron/assets/7817881/fcf4f9c5-121d-48d7-bfd2-8b523b96200f)

I'm still undecided as to whether sourcing the entire file vs run line/selection should be the first/default option -- in RStudio we have two separate buttons (with slightly different icons), and maybe that's what we decide we want for Positron too. Either way I do think we should add this command in those three places for now, as it increases the discoverability of the keyboard shortcut.

**Comment by juliasilge** [comment]
Just got a request for this feature for R.

**Comment by jonvanausdeln** [comment]
Just tried on [2024.09.0-17](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-17) on Windows 11, but I only see run selection, I don't see the additional options, such as "Source R File".  Note for the context menu, it doesn't matter if I have a line of code selected or not.. the only option available is "Run Selection in Console"


![image](https://github.com/user-attachments/assets/8d26f687-417c-4510-adb7-994a8ff4f1d0)

**Comment by jmcphers** [comment]
@jonvanausdeln Are you in an R package? The Source R File command was removed for R packages. Discussion in https://github.com/posit-dev/positron/pull/4567

**Comment by jonvanausdeln** [comment]
@jmcphers That seems to be somewhat of the issue.  I had the repo [qa-example-content](https://github.com/posit-dev/qa-example-content) opened.  This in itself is not an R Package, but does have an R package directory inside of it.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-17](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-17)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 



Run selection now appears on all 3 places 

- the context menu (right click menu)
- the command palette
- the toolbar menu


### Link(s) to TestRail test cases run or created:

**Comment by jennybc** [comment]
It is likely that this DESCRIPTION file should specify the `Type` field, so that the `qa-example-content` project itself is not mistaken for a package (even though some of the workspaces it *contains* are):

https://github.com/posit-dev/qa-example-content/blob/main/DESCRIPTION

"Package" is really the main official `Type`, so you just need to make sure you put anything *other* than "Package" here. Apparently "Frontend" is also recognized and means something. I think we should put something like ... "TestAssets"? I'm not sure what the constraints are, if any, e.g. around characters or whitespace.

Anecdotally on GitHub I see a smattering of "Book", "Shiny", "Compendium", etc. for people using DESCRIPTION in non-package projects.

---

Relevant R package detection code in positron-r:

https://github.com/posit-dev/positron/blob/df4656b46ca4675e8c58d1cad9c8b1a29303264b/extensions/positron-r/src/contexts.ts#L19-L22

Official documentation around the `Type` field:

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-types-1
