### ISSUE TITLE
R language runtime does not flush stdout into output runtime messages for long-running code fragments

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#210]
Long-running code fragments may generate output as they execute. For example, if you run:

```R
for (i in 1:10) { print(sprintf("This is line %d", i)); Sys.sleep(1); }
```

in RStudio, you will see output every second for 10 seconds. Here's a little movie of that:

https://user-images.githubusercontent.com/853239/221022730-bb9c0684-504c-4ef3-b515-d438e99c3b8f.mov

If you run this code fragment in the R language runtime in Positron, none of the output shows up until the code fragment finishes executing. Here's a little movie of that:

https://user-images.githubusercontent.com/853239/221023144-fe3ef0b0-6914-4a07-acc8-c63ad8ab4f2d.mov

You can also see this by trying to use the R progress library:

```R
install.packages("progress")

library(progress)
pb <- progress_bar$new(total = 100)
for (i in 1:100) {
  pb$tick()
  Sys.sleep(1 / 100)
}
```

In RStudio, we get output every 1/100th of a second which draws the progress bar.

In the R language runtime in Positron, all we receive is an empty line for this code fragment, because that's the end result of rendering the progress bar - once it reaches 100% it disappears by rendering an empty line.

**Comment by jmcphers** [comment]
Reported again in https://github.com/posit-dev/positron/issues/4501.

**Comment by lionel-** [comment]
The original issue (output not being streamed) has been fixed in https://github.com/posit-dev/positron/pull/230 (see also follow-up changes in https://github.com/posit-dev/ark/pull/405, relevant because of the distinction between auto-print and user output, only the latter being streamed).

But the progress bars from the `progress` package still do not work. No output is ever emitted from those. So I'm going to mark this as Ready for verification and reopen the other issue to discuss the issue with progress bars.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-83
    OS Version          : OSX

### Test scenario(s) 

for (i in 1:10) { print(sprintf("This is line %d", i)); Sys.sleep(1); }

Link(s) to TestRail test cases run or created:
N/A
