### ISSUE TITLE
Plots: HTML content still displays, even when plots pane is closed

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#2170]
## Positron Version:

positron dev, main, as of commit 4cde239f31cfe3b7f773efdc683b71032f530643

## Steps to reproduce the issue:

1. create HTML plot, eg

```python
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig
```

2. Collapse variables pane
3. toggle plots pane

https://github.com/posit-dev/positron/assets/54685329/65028707-2ded-4664-8d16-c4251f41ec15

## What did you expect to happen?

no plot when pane closed. this only seems to occur when the Variables pane is also closed.

**Comment by juliasilge** [comment]
Came up with a user here: https://github.com/posit-dev/positron/discussions/3989#discussioncomment-10037028

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-81
    OS Version          : OSX

### Test scenario(s) 

Plot no longer visible when pane is closed.  Worth noting, though, that after a pan is closed and reopened the plot does not redraw until the positron window is resized.  I will see if this issue is already filed and file it if not.

Link(s) to TestRail test cases run or created: 
N/A
