### ISSUE TITLE
remotes ssh error

### ISSUE THREAD

**Issue by Liripo** [posit-dev/positron#3687]
## Positron Version: `1.90.0`

![image](https://github.com/posit-dev/positron/assets/54770415/4dbdacc2-fed9-4c5f-9718-8ff6df431315)

File Error：`https://github.com/VSCodium/vscodium/releases/download/1.90.0./vscodium-reh-linux-x64-1.90.0..tar.gz`

**Comment by sjmgarnier** [comment]
I can confirm the problem. The Positron version number is missing the last bit required to match it to the VSCodium version number (1.90.0.24158 in this particular case).

**Comment by jmcphers** [comment]
Unfortunately, even if the version number were there, this wouldn't work because Positron's front end is not compatible with VS Codium's back end (which is what open-remote-ssh is trying to install). To make this work, Positron needs to build/host its own Remote Extension Host (that's the `-reh-` in the URL) binaries. 

This is tracked in #2307.

**Comment by sjmgarnier** [comment]
@jmcphers Thanks for the info. I guess I'll stick to VSCode a little while longer.

**Comment by andrewheiss** [comment]
@sjmgarnier It turns out that it is possible to connect remotely with a little bit of manual configuration: https://github.com/posit-dev/positron/issues/2307#issuecomment-2212869418

**Comment by sjmgarnier** [comment]
@andrewheiss Thanks. I tried and it indeed works well to connect to the server. But without an interpreter, it's not (yet) useful. I looked into the settings but couldn't find a place to specify an interpreter manually.
