### ISSUE TITLE
Enable RPM builds once again

### ISSUE THREAD

**Issue by lbarqueira** [posit-dev/positron#3715]
Hi, congrats for this IDE.

I am not able to install on fedora 40. Could you please comment?

Thank you

**Comment by wesm** [comment]
RPM builds are temporarily disabled but they will return in the future, see related https://github.com/posit-dev/positron/pull/3641.

**Comment by smaanan** [comment]
In the [releases page](https://github.com/posit-dev/positron/releases) there are (along with `.exe`, `.deb` and `.dmg` files) `.tar.gz` and `.zip` files. Can these be somehow used to install/build positron IDE in Fedora Linux?

**Comment by juliasilge** [comment]
@smaanan since that's the code that is used to build the app, it can be used that way, yes, but we don't really recommend you going down that path because of some remaining issues as outlined in https://github.com/posit-dev/positron/issues/1619#issuecomment-1964637961. Unfortunately we aren't going to be able to offer support for you as a user getting such a build going.

**Comment by smaanan** [comment]
@juliasilge thank you.

**Comment by juliasilge** [comment]
I'm bumping this to Triage so we can talk about when to prioritize the work for making the RPM builds available again. They _are_ already being generated in our private builds repo.

**Comment by petetronic** [comment]
This issue is now pending QA readiness

**Comment by jonvanausdeln** [comment]
I just ran the latest daily through its paces on Fedora 40 things worked as expected.  I'm good with add in the .rpm package to the next push to the repo. This will allow us to get more use feedback, etc.
