### ISSUE TITLE
New R project experience should use better default name

### ISSUE THREAD

**Issue by JosiahParry** [posit-dev/positron#3735]
Creating a new project there are two noticeable issues: 

1. The color theme is ignored to some degree and the dark positron theme is used in some parts making it tough to read
2. The default name uses lower camel case which is not standard R style
3. 
<img width="700" alt="image" src="https://github.com/posit-dev/positron/assets/13534508/b06478d5-cab9-4547-8330-491cac83776d">

**Comment by sharon-wang** [comment]
Thanks for taking the Project Wizard for a spin @JosiahParry!

I've opened https://github.com/posit-dev/positron/issues/3799 to capture issue 1 more broadly across our modals/popups.

For issue 2, I'm curious about your thoughts on the following:
- Did you end up using "myRProject" as your project name, or did you end up typing something else?
- What format would have been more expected as the default project name? Maybe "myrproject" or "my-r-project"?
- What if the project name input was blank instead, so you'd need to type in a project name (no default)?
- Would a "randomly" generated project name serve your purposes?

**Comment by juliasilge** [comment]
Using lower camel case _is_ really unusual for an R project. I would say let's switch to "my-r-project". 👍

**Comment by jonvanausdeln** [comment]
If the default project name changes, please check the new-project-wizard smoke tests. They will need to be changed to look for the new name.

**Comment by JosiahParry** [comment]
Sorry @sharon-wang ! I did not end up using the wizard's created name. I suspect I won't actually ever use it again since I'm more of a enter the terminal and: 

```shell
mkdir my-r-project
cd my-r-project
positron . 
```

That said, there is an almost 0% chance that any project I make that uses R will have a lower-camel casing 😜 

I thin `my-r-project` would be a good alternative!

**Comment by jennybc** [comment]
It's worth noting that `my-r-project` would not be a legal name for an R package (at least if you want to pass `R CMD check`). So if we're going to offer a default, we might want to consider that, in terms of digging a pit of success.

https://r-pkgs.org/workflow101.html#name-your-package

That being said, I think any use of the default name is basically by definition a toy experiment, because for real work, I'd expect the user to have a better name than our default.

**Comment by sharon-wang** [comment]
Thanks everyone for the feedback! It sounds like we're mainly in favour of `my-r-project`, so here's a summary of the implementation plan and some notes which may be helpful for https://github.com/posit-dev/positron/issues/3364.

### To Implement
- change the default R project name to `my-r-project` because lower camel casing (i.e. `myRProject`) is very atypical for an R project
- update the [Project Wizard Smoke Tests](https://github.com/posit-dev/positron/blob/main/test/smoke/src/areas/positron/new-project-wizard/new-project.test.ts) to expect the new default R project name

### Notes on UX
- users are likely to replace the default project name with something more relevant to what they are creating
- we could offer to generate a "random" project name for the user, but if the user typically opts to replace the default name anyways, implementing this may not have an outsized impact
- `my-project-name` would not be a valid name for an R Package, so we could align with R Package naming standards in case the user ends up turning the project into a package
    - We may support "R Package" in the Project Wizard in the future, so maybe it's okay to keep the project name default `my-r-project` and the default name for an R Package could be something like `myrproject` (we could also do some input validation to check if the package name is already taken on CRAN/Bioconductor)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-41
    OS Version          : OSX

### Test scenario(s) 

Validated with automation against main on same day release was created.

Link(s) to TestRail test cases run or created:
