### ISSUE TITLE
Licensing plans

### ISSUE THREAD

**Issue by grantmcdermott** [posit-dev/positron#3780]
Hi folks,

I'm trying to understand/gauge the long-term [licensing](https://github.com/posit-dev/positron/wiki/Licensing) plans for Positron. Unfortunately, the Elastic license is among the list of prohibited licenses at Amazon (my employer). I imagine that this restriction holds at other large tech firms and possibly even university HPCs.

As you probably know, A-GPL is also among the _verboten_ licenses at most tech firms, which precludes the use of the free RStudio desktop client. However, we can at least purchase a commercial license with RStudio Pro (approved for internal use). Do you have similar plans to license a commercial version of Positron that would make it possible to use the IDE in these more restrictive environments?

Thanks.

**Comment by jthomasmock** [comment]
We currently don't have a "Positron Desktop Pro", but I'm very aware of some organizations purchasing RStudio Desktop Pro to move to a commercial license instead of AGPL. So if Elastic ends up being a blocker in some specific organizations, even for internal, non-hosted use, I could see us providing an alternate commercial license. 

Thanks!

**Comment by grantmcdermott** [comment]
Great, thanks Tom. I'll do some more investigating with our legal team to see how this plays out and report back if any changes.

Closing for now in the interest of reducing GitHub noise for the dev team.
