### ISSUE TITLE
Interpreters in miniforge are not detected

### ISSUE THREAD

**Issue by aldotapia** [posit-dev/positron#3791]
## Steps to reproduce the issue:

1. Open Positron
2. Creck interpreters

## What did you expect to happen?

Identify R installation and activate the R interpreter, Since I have R 4.4.1 installed

## Were there any error messages in the output or Developer Tools console?

There are no error messages in either output or console. I can only see Python interpreters:

<img width="401" alt="Captura de pantalla 2024-07-01 a la(s) 8 17 12 p  m" src="https://github.com/posit-dev/positron/assets/23053094/ade6bed0-ca90-45e8-9ede-5e28b99df8d3">

**Comment by juliasilge** [comment]
Can you look in the Positron R Extension output channel and share what you see there?

![r-ext-logs](https://github.com/posit-dev/positron/assets/12505835/e3167f67-735b-4968-bc18-dea66ddde8cf)

You can even attach the whole file here as a `.log` file if you do "Open Output in Editor" and then find/save the file.

**Comment by aldotapia** [comment]
Sure, it's the following:

```
2024-07-01 23:48:29.590 [info] Log level: Debug
2024-07-01 23:48:29.590 [info] Refreshing testthat status
2024-07-01 23:48:29.590 [info] Not working in an R package
2024-07-01 23:48:29.590 [info] Context key 'testthatIsConfigured' is 'false'
2024-07-01 23:48:29.591 [info] Context key 'testthatHasTests' is 'false'
2024-07-01 23:48:29.594 [info] Resolved R binary at /Users/aldotapia/miniforge3/bin/R
2024-07-01 23:48:29.600 [info] Candidate R binary at /Users/aldotapia/miniforge3/bin/R
2024-07-01 23:48:29.600 [info] R installation discovered: {
  "valid": true,
  "supported": false,
  "binpath": "/Users/aldotapia/miniforge3/bin/R",
  "homepath": "/Users/aldotapia/miniforge3/lib/R",
  "semVersion": {
    "options": {},
    "loose": false,
    "includePrerelease": false,
    "raw": "4.1.2",
    "major": 4,
    "minor": 1,
    "patch": 2,
    "prerelease": [],
    "build": [],
    "version": "4.1.2"
  },
  "version": "4.1.2",
  "arch": "x86_64",
  "current": true,
  "orthogonal": true
}
2024-07-01 23:48:29.600 [info] Candidate R binary at /Library/Frameworks/R.framework/Versions/4.2/Resources/bin/R
2024-07-01 23:48:29.600 [info] R installation discovered: {
  "valid": true,
  "supported": true,
  "binpath": "/Library/Frameworks/R.framework/Versions/4.2/Resources/bin/R",
  "homepath": "/Library/Frameworks/R.framework/Resources",
  "semVersion": {
    "options": {},
    "loose": false,
    "includePrerelease": false,
    "raw": "4.4.1",
    "major": 4,
    "minor": 4,
    "patch": 1,
    "prerelease": [],
    "build": [],
    "version": "4.4.1"
  },
  "version": "4.4.1",
  "arch": "x86_64",
  "current": false,
  "orthogonal": false
}
2024-07-01 23:48:29.600 [info] Candidate R binary at /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/bin/R
2024-07-01 23:48:29.600 [info] R installation discovered: {
  "valid": true,
  "supported": true,
  "binpath": "/Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/bin/R",
  "homepath": "/Library/Frameworks/R.framework/Resources",
  "semVersion": {
    "options": {},
    "loose": false,
    "includePrerelease": false,
    "raw": "4.4.1",
    "major": 4,
    "minor": 4,
    "patch": 1,
    "prerelease": [],
    "build": [],
    "version": "4.4.1"
  },
  "version": "4.4.1",
  "arch": "x86_64",
  "current": false,
  "orthogonal": false
}
2024-07-01 23:48:29.600 [info] Filtering out /Library/Frameworks/R.framework/Versions/4.2/Resources/bin/R: not current and also not orthogonal.
2024-07-01 23:48:29.600 [info] Filtering out /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/bin/R: not current and also not orthogonal.
2024-07-01 23:48:29.600 [info] Filtering out /Users/aldotapia/miniforge3/bin/R: version is < 4.2.0
```

Perhaps conda R version is conflicting here, since R Extension found R v4.4

**Comment by aldotapia** [comment]
Positron detected R after uninstalling `r-base` from miniforge3 base env (yes, my bad). I don't know if I should close this issue, since now I'm looking at Python interpreters detected and the only one that shows up from miniconda3 is the base environment (I have 19 miniforge3 environments). I even set up the default Python interpreter to one of them (`/Users/aldotapia/miniforge3/envs/ads` for example) and when I restart Positron it changes to `~/.pyenv/versions/3.8.16/bin`.

I have no issues with anaconda3 or pyenv, so I suspect it's related to miniforge3

**Comment by roaldarbol** [comment]
I think this issue is worthwhile keeping open - might need a renaming though. To me the issue seems that Positron isn't supporting the `r-base` installation, which is a pity since it's a great way of having a reproducible environment. So ensuring that other R installations are discoverable, also conda installations.

For the Python interpreters, Positron uses the `vscode-python` extension, and they might  be having some issues with `miniforge3` (https://github.com/microsoft/vscode-python/issues/23655) (and do not currently support `micromamba` yet (https://github.com/microsoft/vscode-python/issues/20919#issuecomment-1563340654)). So on the Python side I'd direct an issue there. :-)

**Comment by wesm** [comment]
I also use miniforge3 so I agree that we should make Positron robust to discovering both R and Python environments originating out of conda-forge (even if they're installed in the base environment)

**Comment by lionel-** [comment]
Can you try installing R >= 4.2 on miniforge? I think the one currently installed doesn't show up because it's an unsupported version:

```
Filtering out /Users/aldotapia/miniforge3/bin/R: version is < 4.2.0
```

**Comment by lionel-** [comment]
So your _current_ installation is the miniforge R, which is unsupported because it's < 4.2.

Then you have two other installations which are neither current nor _orthogonal_ (which means they are not safe to run if not current), which were also discarded during discovery.

Besides installing a newer version of R on miniforge, you can also make your other installations of R orthogonal by running

```
rig system make-orthogonal 
```

See https://github.com/r-lib/rig for how to install rig. This would at least allow Positron to run these other installations of R that meet the version requirement.

We plan to make it easier to understand what's going on when an install of R is unsupported, see https://github.com/posit-dev/positron/issues/1397

**Comment by jennybc** [comment]
We've figured out that positron-r is behaving as intended here and, specifically, that we can discover an interpreter in miniforge. The problem is that the intersection of supported R installations (version >= 4.2) and "usable" installation (either the current version of R or a so-called orthogonal R installation) is the empty set right now on this user's system.
