### ISSUE TITLE
Consider improve the Ipython Console

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#3802]
The Ipython console, which is used in DataSpell IDE really go beyond.
First, the already run command is numbering, according with syntax highlighting
Secondly, viewing data is not just priting it. The data is printed with functionalities and some summary statistics, similar to what it can do in Jupyter Notebook of the IDE

![image](https://github.com/posit-dev/positron/assets/63569637/660c8e6d-b533-46cd-a233-242cec4555e4)

**Comment by wesm** [comment]
Thanks for trying Positron! Since the project is still in its early stages, there are many features which have not been completed yet, like summary statistics and visual profiles in the data explorer, but these are on the roadmap.

**Comment by ntluong95** [comment]
That's very great to hear. Also glad to know an author of Pandas has joined the project, so very looking forward to a bright future

**Comment by juliasilge** [comment]
We are tracking syntax highlighting for the Console in #243, if you would like to upvote or add additional context on what you like about DataSpell.

For more fully featured viewing of your data, we are focusing on the [Data Explorer](https://github.com/posit-dev/positron/wiki/Data-Explorer) in the short term, rather than more features for printing in the console. You can see [some of what is planned here](https://github.com/posit-dev/positron/issues?q=is:issue+is:open+label:%22area:+data+explorer%22).
