### ISSUE TITLE
Shift-Command-C not working for 'Toggle Line Comment'

### ISSUE THREAD

**Issue by jacobmgreer** [posit-dev/positron#3830]
Type: <b>Bug</b>

Shift-Command-C in Positron on a Mac seems to toggle opening Terminal rather than toggling a line comment.

VS Code version: Positron 1.90.0 (Universal) (a893e5b282612ccb2200102957ac38d3c14e5196, 2024-06-26T02:08:06.673Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (5.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jmcphers** [comment]
Do you have the RStudio keymap enabled?  If you go to Settings and check this box, you should get the behavior you expect for this shortcut:

<img width="650" alt="image" src="https://github.com/posit-dev/positron/assets/470418/70368298-a88d-45f9-b486-ee43b9de9e4e">

(otherwise you'll get the default VS Code behavior for this key combo, which is indeed to open a terminal)

**Comment by jacobmgreer** [comment]
Ah, that did it!
