### ISSUE TITLE
Can not recognize R installed in other paths on Windows

### ISSUE THREAD

**Issue by LeiGuo0812** [posit-dev/positron#3868]
Hi everyone,

I am currently using Windows 10 and R 4.4.0. My RStudio works well. However, when I use Positron, it doesn't correctly recognize my R interpreter. I can't run any R code in Positron. I believe this is mainly because my R is installed in D:\ rather than the default C:\ path. This issue persists even after I add the bin folder of R to the PATH system variable.

I wonder if there are any workarounds or solutions?

Thanks in advance.

**Comment by bionicturtle** [comment]
I'm having exactly the same problem. I am looking for, but cannot find, a setting/preference that would allow me to point to my R executable

**Comment by jennybc** [comment]
There is a relevant discussion in https://github.com/posit-dev/positron/discussions/3677.

We do plan to start looking on the PATH on Windows (which is already tracked in #3702), in addition to the registry. In the meantime, if Posistron has permission to read the registry and the current R version is advertised there, we should pick it up.

#3787 is also related.

Closing because I think we've got all of the captured elsewhere.
