### ISSUE TITLE
Authentication problem with GitHub Pull Requests extension

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3873]
I get this warning message from the GH PR extension, which I don't get in VSCode. My question is whether we need some additional settings in our GitHub repos (I couldn't find anything related yet), or if this is a Positron bug?

![image](https://github.com/posit-dev/positron/assets/26301769/fd5774c6-46d0-4a88-a70f-7cdf6245580a)

**Comment by juliasilge** [comment]
I expect this is related to #3355. 

@jmcphers can you take a look when you get a chance and see if we can change the OAuth app so it plays nicer with organizations like this one?

**Comment by jmcphers** [comment]
Yes, I think this is related to #3355. That change gave Positron its own third-party app identity. If the organization only allows access by approved third-party apps, then the organization needs to add Positron to the approved list.

@strengejacke This would be an organization level (rather than repo level) change. You can find instructions here: https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization

**Comment by strengejacke** [comment]
But how can we add Positron to that list?

**Comment by jmcphers** [comment]
Are you able to create an approval request? https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

**Comment by strengejacke** [comment]
It's a bit hidden, not quite exactly what the docs say, but I found it and it works, thanks!

**Comment by jmcphers** [comment]
Great, glad to hear it!
