### ISSUE TITLE
The built-in Positron Jupyter Notebook are not recognizable by Data Wrangler extension 

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#3885]
### Run built-in Positron Notebook by creating a new .ipynb file, and run normally
![image](https://github.com/posit-dev/positron/assets/63569637/8d86951c-f7f0-4230-9f13-ced4e2ff34ea)

### Run Notebook created from Jupyter PowerToy
First, install  Jupyter PowerToy and Data Wrangler extension from *.vsix file
The Jupyter PowerToy provides this pane, which allow us to create a new notebook from several interpreters

![image](https://github.com/posit-dev/positron/assets/63569637/41398d7d-f9fc-4282-8402-edee69a3ff15)

After creating new notebook, run the same script. As noted, Jupyter PowerToy added 2 buttons to explore data, but variables are now not registering in variable pane
<img width="1272" alt="image" src="https://github.com/posit-dev/positron/assets/63569637/ee08f580-c6e0-4161-9f89-28ba8d717dd4">

Also there was an error warning:
Error got from creating unusal notebook
![image](https://github.com/posit-dev/positron/assets/63569637/e358c979-3fa7-42f9-9b6e-6f9209f12fac)

Since the extension is very helpful, I hope that Positron can support it to integrate good things into the system :)

**Comment by juliasilge** [comment]
We can keep this open to get feedback for prioritization on supporting the Data Wrangler extension, but in the meantime, we suggest you check out the [Data Explorer](https://github.com/posit-dev/positron/wiki/Data-Explorer) for these kinds of tasks.

**Comment by juliasilge** [comment]
Hmmm, actually, the Data Wrangler extension is not available from OpenVSX because it is a [proprietary Microsoft extension](https://github.com/microsoft/vscode-data-wrangler?tab=License-1-ov-file#readme). Given that situation, I don't think we can/are able to support this use case. You can [read more about extensions on OpenVSX here](https://github.com/microsoft/vscode-data-wrangler?tab=License-1-ov-file#readme).
