### ISSUE TITLE
Sth. weird happen

### ISSUE THREAD

**Issue by trafficfan** [posit-dev/positron#3924]
## Positron Version:
版本: Positron Version: 2024.07.0 (system setup) build 2024.07.0-14
Code - OSS Version: 1.90.0
Commit: b750305d0e9079e1a6d4e0b1d78daa70964b0cb8
Date: 2024-07-04T03:20:34.533Z
提交: 29.4.0
日期: 122.0.6261.156
Electron: 20.9.0
ElectronBuildId: 12.2.281.27-electron.0
Chromium: Windows_NT x64 10.0.22631
Node.js: undefined
V8: undefined
OS: undefined
## Steps to reproduce the issue:

1. read sth. with tidyverse
2. use the janitor 

## What did you expect to happen?
sth. should happen in RStudio

## Were there any error messages in the output or Developer Tools console?
![image](https://github.com/posit-dev/positron/assets/149685680/67fe2fb0-12ba-4179-a453-0d40d3b56923)
It's weird

**Comment by juliasilge** [comment]
I am able to run code in an R notebook using janitor without a problem:

![janitor](https://github.com/posit-dev/positron/assets/12505835/4f48146b-0678-447e-b717-c336080e9d39)

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. Thanks! 🙌

**Comment by petetronic** [comment]
Also another thing @trafficfan could try to help narrow it down - it looks like you're using R devel 4.5.0 (and perhaps you had to compile packages from sources). Have you tried a stable 4.4.0 or 4.4.1 release of R? Does it happen with another simpler .xlsx?

**Comment by trafficfan** [comment]
Looks like an R4.5 issue, not found in R4.4 conditions
