### ISSUE TITLE
Newly created pyenv envs not getting picked up by Positron

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#3944]
## Steps to reproduce the issue:

1. Create a new pyenv env such as `pyenv install -v 3.12.1`
2. Completely restart positron
3. Look for new version

## What did you expect to happen?
Expected new version to be available for use

## Were there any error messages in the output or Developer Tools console?
I do not see any.

**Comment by jonvanausdeln** [comment]
I can also reproduce this on Windows (I even rebooted the machine)

Additionally, I see this in terminal in Positron:  


![image](https://github.com/posit-dev/positron/assets/6433789/0c37616b-ea9d-4a19-aaa6-6702b663629e)

But in my normal windows terminal I see:

![image](https://github.com/posit-dev/positron/assets/6433789/52dc2366-128b-4580-8a96-4f8b7d112f3e)

Note - my newly added pyenv version was 3.10.10

**Comment by timtmok** [comment]
Is it not visible in the interpreter selector or when running the `Python: Select Interpreter` command?

**Comment by testlabauto** [comment]
@timtmok I am not seeing new pyenvs via the selector and not seeing them with the `Python: Select Interpreter` command.

**Comment by jonvanausdeln** [comment]
I just did an uninstall.. and deleted %APPDATA%\Roaming\Positron... then installed. Now I'm seeing all of the interpreters

**Comment by timtmok** [comment]
I happen to not see them in the selector but it does show up when using the command. Then it shows in the selector. I'm using `2024.07.0 (Universal) build 17`.

**Comment by testlabauto** [comment]
Oh, you are correct, @timtmok ... I can get to them from the command and that makes them show up in the selector.

**Comment by seeM** [comment]
If it's visible in the command but not in Positron, that's still a bug. It means that the Python extension discovers a new interpreter, but we aren't correctly notifying Positron.

The code responsible is here: https://github.com/posit-dev/positron/blob/bbacfc47a21fe71dbd62bffd2752e0a7b2042578/extensions/positron-python/src/client/positron/manager.ts#L69

For comparison: when you select an interpreter via the command, the code that then registers it with Positron is here: https://github.com/posit-dev/positron/blob/bbacfc47a21fe71dbd62bffd2752e0a7b2042578/extensions/positron-python/src/client/positron/manager.ts#L81

**Comment by isabelizimm** [comment]
This is happening since the quickpick (`cmd+shift+p` -> `Python: Select Interpreter`) refreshes the interpreter list the first time you open it up; subsequent refreshes have to be manually triggered.

So, a repro would look something like 

1. Create new pyenv in terminal `pyenv virtualenv 3.11.4 my-new-env` See that it does **not** show up in Positron interpreter selector, since no refresh has been triggered.
2. Open Command Palette -> `Python: Select Interpreter` quickpick to trigger refresh. See interpreter in Positron interpreter and command palette selector.
3. Create another pyenv in terminal `pyenv virtualenv 3.11.4 my-new-env-2`. Cannot see in quickpick OR Positron interpreter dropdown.
4. Click refresh button in quickpick. See interpreter in quickpick and Positron interpreter dropdown

https://github.com/posit-dev/positron/blob/bbacfc47a21fe71dbd62bffd2752e0a7b2042578/extensions/positron-python/src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts#L197-L210

To keep parity between these lists, a few options are:

1. Do not refresh interpreters on first quickpick open post-discovery. This would force users to manually refresh from the quickpick each time they would like to see a new interpreter, but the lists in each location would always be the same. It would be nice to have the discovery refresh button available in the dropdown, imo
2. Refresh when users click the `...` in the Positron interpreter selector (and always refresh the quickpick when opened), which might be slow.

Related: https://github.com/posit-dev/positron/issues/2003

**Comment by seeM** [comment]
@isabelizimm could we trigger a refresh on extension load, and maybe in that case the interpreter picker won't trigger another one?

I agree that it could be helpful to have a way to manually refresh/redo discovery in Positron via the UI, which we could track separately.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-1](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-1)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 



After installing new pyenv, it appears in list after any of these:
* Open quickpick "Select Interpreter" and then "refresh"
* Restart Positron
The quickpick list and Positron drop down are both correctly in sync.

Same is true for uninstalling a pyenv version
