### ISSUE TITLE
Matplotlib plots with subplots/ridgeline is not handled well

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4040]
## Positron Version: 2024.07.0 (Universal) build 52
Code - OSS Version: 1.90.0
Commit: eee2ff0fdcb422608b5181338e6204cdb5e311cd
Date: 2024-07-16T04:40:30.193Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Steps to reproduce the issue:

1. Run this code

<details>

```python
# getting necessary libraries
# import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

# getting the data
temp = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2016-weather-data-seattle.csv') # we retrieve the data from plotly's GitHub repository
temp['month'] = pd.to_datetime(temp['Date']).dt.month # we store the month in a separate column

seattle_weather = temp

# we define a dictionnary with months that we'll use later
month_dict = {1: 'january',
              2: 'february',
              3: 'march',
              4: 'april',
              5: 'may',
              6: 'june',
              7: 'july',
              8: 'august',
              9: 'september',
              10: 'october',
              11: 'november',
              12: 'december'}

# we create a 'month' column
temp['month'] = temp['month'].map(month_dict)

# we generate a pd.Serie with the mean temperature for each month (used later for colors in the FacetGrid plot), and we create a new column in temp dataframe
month_mean_serie = temp.groupby('month')['Mean_TemperatureC'].mean()
temp['mean_month'] = temp['month'].map(month_mean_serie)

# we generate a color palette with Seaborn.color_palette()
pal = sns.color_palette(palette='coolwarm', n_colors=12)

# in the sns.FacetGrid class, the 'hue' argument is the one that is the one that will be represented by colors with 'palette'
g = sns.FacetGrid(temp, row='month', hue='mean_month', aspect=15, height=0.75, palette=pal)

# then we add the densities kdeplots for each month
g.map(sns.kdeplot, 'Mean_TemperatureC',
      bw_adjust=1, clip_on=False,
      fill=True, alpha=1, linewidth=1.5)

# here we add a white line that represents the contour of each kdeplot
g.map(sns.kdeplot, 'Mean_TemperatureC', 
      bw_adjust=1, clip_on=False, 
      color="w", lw=2)

# here we add a horizontal line for each plot
g.map(plt.axhline, y=0,
      lw=2, clip_on=False)

# we loop over the FacetGrid figure axes (g.axes.flat) and add the month as text with the right color
# notice how ax.lines[-1].get_color() enables you to access the last line's color in each matplotlib.Axes
for i, ax in enumerate(g.axes.flat):
    ax.text(-15, 0.02, month_dict[i+1],
            fontweight='bold', fontsize=15,
            color=ax.lines[-1].get_color())
    
# we use matplotlib.Figure.subplots_adjust() function to get the subplots to overlap
g.figure.subplots_adjust(hspace=-0.3)

# eventually we remove axes titles, yticks and spines
g.set_titles("")
g.set(yticks=[])
g.despine(bottom=True, left=True)

plt.setp(ax.get_xticklabels(), fontsize=15, fontweight='bold')
plt.xlabel('Temperature in degree Celsius', fontweight='bold', fontsize=15)
g.figure.suptitle('Daily average temperature in Seattle per month',
               ha='right',
               fontsize=20,
               fontweight=20)

plt.show()
```

</details>

2. Note the plot appears as flat densities.

![image](https://github.com/user-attachments/assets/391235b4-8e4d-47b2-8c4f-99ba68616914)

## What did you expect to happen?

Observe the proper density plots as well as proper text handling.

Running in Notebook:

![image](https://github.com/user-attachments/assets/208ce57a-2c41-4e0b-9314-88263fbfc035)

Customizing the image with: 1200 x 1200 dimension

<img width="770" alt="image" src="https://github.com/user-attachments/assets/7bab9918-cc84-417c-9e6f-81c2894b386c">

**Comment by seeM** [comment]
There are a few parts to this issue.

### Sizing

The biggest issue is that Positron is totally unaware of the original image size defined in the user's code. The plot here is 1125x900 pixels, but the "auto" sizing policy doesn't know that and ends up using the size of the Plots pane.

**Recommendation:** When the kernel opens the plot comm, it should include the plot's preferred size.

How exactly we decide to use that in the auto sizing policy is not immediately obvious. A decent starting point could be to _always_ use the original plot size if it's known and if it differs from the default Matplotlib plot size. We can start with that change and see what user feedback we get.

### Bounding box

When you render a Matplotlib figure, you can set the specific bounding box to render. You can also request a "tight" bounding box i.e. one that tightly fits all of the figure's elements. This is convenient because no figure element will be clipped, but you can no longer guarantee the exact figure size. For example, the actual Seaborn plot here is 1125x900 pixels, but using a tight bounding box it ends up at 1147x892 pixels.

Jupyter's matplotlib backend uses a tight bounding box. Our backend does not, so that we can offer exact pixel sizing.

**Recommendation:** I don't think we need to change anything here, for now.

### Layout

Histograms overlap in the Jupyter version but not in Positron, because we use a "tight" _layout_ and they don't. This is not the same as the tight bounding box discussed in the previous section. A tight layout repositions figure _elements_ so that they don't overlap – it does not affect the figure's bounding box and thus the rendered image size.

We started using a tight layout [here](https://github.com/posit-dev/positron/pull/2592/files#diff-878101b98350ace4109ca0d94dc0f83090a005477f2b1a08725e8840af73853dR176), when we fixed the non-exact sizing issue.

You kind of have to use either a tight layout or a tight bounding box otherwise Matplotlib will often clip axes/titles with the default settings.

For example, given this plotting code:

```python
import numpy as np
import matplotlib.pyplot as plt

v = np.arange(365, 0, -1)

fig, ax = plt.subplots()
ax.set_xlabel('Day of the year')
ax.set_ylabel('Days until New Year\'s Eve')

plt.xlim(0, 365)
plt.ylim(1, 365)

plt.plot(v)
```

Here's what it looks like with various configurations:

**None**; both the x- and y-axis labels are clipped:

<img src="https://github.com/user-attachments/assets/d52d13bf-0b96-433d-b43b-ab4c62821bb4" width="200">

**Tight layout**; the figure size hasn't changed, but elements are resized and repositioned to fit the bounding box:

<img src="https://github.com/user-attachments/assets/b3754fc2-686e-490e-9d1d-c797fe041278" width="200">

**Tight bounding box**; elements aren't repositioned or resized, but the bounding box is resized to fit all elements:

<img src="https://github.com/user-attachments/assets/2e32246e-b160-4469-9980-0c5547ce0386" width="200">

**Recommendation:** I don't think we need to change anything here either.

**Comment by jmcphers** [comment]
> Recommendation: When the kernel opens the plot comm, it should include the plot's preferred size.

Adding this feature to the plots comm would also be very useful for R plots; see #3676.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-48
    OS Version          : OSX

### Test scenario(s) 

Original filing code.  Change dimensions to 1200 x 1200

Link(s) to TestRail test cases run or created:
N/A
