### ISSUE TITLE
RPC Timeout sorting small polars dataframe on low resource Ubuntu box (CI)

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4070]
## Steps to reproduce the issue:

Note that this issue is occurring in CI against main so the version above is approximate but very likely accurate.  This is also really tough, if not impossible, to reproduce locally.  The CI machine is pretty low on resources so that is worth noting.

1. Load a simple polars data frame into data explorer.  The automated test is using:

```
import polars as pl

from datetime import date
df = pl.DataFrame(
    {
        "foo": [1, 2, 3],
        "bar": [6.0, 7.0, 8.0],
        "ham": [date(2020, 1, 2), date(2021, 3, 4), date(2022, 5, 6)],
        "a": [None, 2, 3],
        "b": [0.5, None, 2.5],
        "c": [True, None, False],
    }
)
```

2. (Possibly unnecessary step) Filter column foo by "not equal to 1"
3. Sort column foo descending.
4. Note console error after 5 seconds

## What did you expect to happen?

I expected the polars dataframe sort to complete successfully.

## Were there any error messages in the Output panel or Developer Tools console?

ERR RPC timed out after 5 seconds: {"jsonrpc":"2.0","method":"set_sort_columns","params":{"sort_keys":[{"column_index":0,"ascending":false}]}}

**Comment by jonvanausdeln** [comment]
QA Note - We are skipping the offending test in CI. Once this is resolved, it will need to be turned back on.

**Comment by seeM** [comment]
@wesm I believe those asyncio warnings are because we enable debug mode (when the kernel log level is set to debug), causing asyncio to log "slow" callbacks. By default, it logs callbacks longer than 100ms but we can tune that.

Docs: https://docs.python.org/3/library/asyncio-dev.html#debug-mode

---

Currently, if any of our `comm_msg` callbacks error, the kernel throws and the RPC times out. We could instead wrap that in a try-except that returns an RPC error to the client so it can show a more helpful message and give us a better clue about what's going wrong. So this line:

https://github.com/posit-dev/positron/blob/f1734059e27107ccf7c9c87d97202721f432c0d4/extensions/positron-python/python_files/positron/positron_ipykernel/positron_comm.py#L187

Could become something like:

```python
try:
    callback(comm_msg, raw_msg)
except Exception as exception:
    self.send_error(JsonRpcErrorCode.INTERNAL_ERROR, f"Internal error: {exception}")
```

**Comment by testlabauto** [comment]
This Python log is available from the run.  Not sure if its helpful.  It is the log for all basic data explorer python cases. 

[Python.log](https://github.com/user-attachments/files/16315857/Python.log)

**Comment by testlabauto** [comment]
Additionally, I see this log:

[Console Python 3.10.12 (Global).log](https://github.com/user-attachments/files/16315889/Console.Python.3.10.12.Global.log)

**Comment by wesm** [comment]
Cool, I think that gives me enough to work off of, thanks!

**Comment by wesm** [comment]
This appears to be a regression in polars (which isn't pinned in these CI runs -- do you want to pin dependencies?), reporting it here https://github.com/pola-rs/polars/issues/17769. I will open a PR with a workaround for now

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-89
    OS Version          : ubuntu-latest in CI

### Test scenario(s) 

Test now passes again in CI

Link(s) to TestRail test cases run or created: 
Test already created
