### ISSUE TITLE
F1 doesn't open help panel in Quarto chunk

### ISSUE THREAD

**Issue by andrewheiss** [posit-dev/positron#4097]
## Positron Version:

Positron Version: 2024.07.0 (Universal) build 41
Code - OSS Version: 1.90.0
Commit: 9f24124be55ef409fb6b6c75ee80232f298cd56b
Date: 2024-07-12T04:30:16.648Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

---

I'm not sure if this is a Quarto extension issue or a Positron issue, or if it's related to #3753, but the F1 shortcut for help doesn't seem to work in R chunks in Quarto documents on macOS. The documentation *does* show up when hovering over function names, and running `?whatever` in the console works fine too—it's just the F1 shortcut that doesn't do anything (and doesn't emit any console messages either)

Here's a little video:

https://github.com/user-attachments/assets/fbb05547-e0d5-4a3e-b55a-ac441994b788

## Steps to reproduce the issue:

1. Make an R chunk in a Quarto document and type an R function name
2. Place the cursor in the function name and type <kbd>F1</kbd>

## What did you expect to happen?

I was hoping the help panel would appear

## Were there any error messages in the Output panel or Developer Tools console?

Nope!

**Comment by juliasilge** [comment]
We had a related problem in #1645 where _all_ language features didn't work and thought we had fixed that, including <kbd>F1</kbd> help.

**Comment by andrewheiss** [comment]
Huh, weird! All other language features work in both source and visual editor modes, just not F1

https://github.com/user-attachments/assets/8923562c-790d-4336-a26e-3e405f434458

**Comment by juliasilge** [comment]
This is _not_ an R only problem. For Python as well, <kbd>F1</kbd> help works in a regular `.py` file but does not work in a Quarto file.

**Comment by mrzeszut** [comment]
You can easily solve the F1 problem in quarto.  Move the `quarto: help` window to the panel on the right, a tab will be added. Just drag the window with the mouse I on printsrc:)    
![Image](https://github.com/user-attachments/assets/fb6ee13f-f091-46ad-a3e5-85dc31f5fe93)

**Comment by juliasilge** [comment]
@mrzeszut That's a different help server entirely, so not quite what this is about FYI. You definitely can move it around as needed, though!

**Comment by juliasilge** [comment]
## QA Notes

To see this fixed, you will need _both_ the version of Positron that has #5292 _and_ the version of the Quarto extension that has quarto-dev/quarto#599. 

> [!NOTE]  
> Heads up to our valued beta folks! This isn't in a publicly available build of Positron as of my writing but will be early next week.

You can get the appropriate version of the Quarto version [from the artifact here](https://github.com/quarto-dev/quarto/actions/runs/11751844180) (download, unzip, install the `.vsix`, restart Positron). Then you can use <kbd>F1</kbd> to bring up Positron help in a `.qmd` that uses R.

Python does not work because <kbd>F1</kbd> help is broken for Python entirely as now tracked in https://github.com/posit-dev/positron/issues/5290.

I did not change anything about the `quarto-assist` webview, which is what is shown in https://github.com/posit-dev/positron/issues/4097#issuecomment-2427178059. I don't believe that was ever bound to <kbd>F1</kbd> in Quarto but rather [it is bound to <kbd>Cmd/Ctrl</kbd>+<kbd>F1</kbd>](https://github.com/quarto-dev/quarto/blob/69fce357ec669e9579a53551b26ea5a9b8c14c55/apps/vscode/package.json#L599).

Given that we made some other architectural changes in quarto-dev/quarto#599, it would also be great to run through a bit of spot testing of hover, statement range provider, signature help, and completions in `.qmd` files. I have also checked all these, but not a bad idea for someone else to confirm!

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-21](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-21)
OS Version(s) :  Windows 11

### Test scenario(s) 

`F1` opens help as expected R quarto chunk

### Link(s) to TestRail test cases run or created:
