### ISSUE TITLE
Several Potential Improvements on Positron?

### ISSUE THREAD

**Issue by AxisJu** [posit-dev/positron#4260]
As a heavey user of Rstudio and VSCode, we love positron!
Also implemention of the below functions would be better~

1. View 'Package' module like in RStudio
2. Outline and code collapse of normal R Script like in RStudio
3. Collapse of 'for' or 'if' in Quarto
4. When selecting a function in the tab, a preview of the function's description is displayed; similarly, when selecting a parameter, a preview of the parameter's description is shown.

Best Regards

**Comment by jmcphers** [comment]
There are issues tracking the first two:

- Packages pane tracked here: #1391 
- Sections for R scripts tracked here: #3822 

For the second two, could you file an individual request for each one with a little more detail? I'm going to close this since for tracking purposes we need to keep each request separate. Thanks for the feedback!
