### ISSUE TITLE
URL reshaping and proxying for Positron localhost URLs on Posit Workbench

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4274]
Positron currently uses localhost URLs to serve content in many places.

- The Help pane, which serves R and Python help pages over a localhost HTTP server
- The Plots pane, which serves interactive plots and HTML content over a localhost HTTP server
- The Viewer pane, which serves interactive applications (Streamlit, Shiny, etc.) as well as HTML content over a localhost HTTP server

These URLs won't be visible to browsers by default in Workbench; they will need to get transformed into proxied Posit Workbench URLs at some point so that they can be loaded in the browser. 

One way to do this might be to use the resolver API, which is part of VS Code upstream and is defined here:

https://github.com/posit-dev/positron/blob/main/src/vscode-dts/vscode.proposed.resolvers.d.ts

Using this API allows us to request that any registered resolvers process the URL before we load it in Positron. Here's an example of where we call the API on the Positron side:

https://github.com/posit-dev/positron/blob/de62b4ee561390e86d0ea5f0d9c09a40d976a80a/src/vs/workbench/services/languageRuntime/common/languageRuntimeUiClient.ts#L155-L161

So a solution could look like this. Here I'm using "Help Server" as an example, but this is akin to what we need to do for each local URL.

```mermaid
graph TD
he[Help Pane] -- localhost URL --> p[Positron]
hs[Help Server] -- localhost URL --> he
p[Positron] -- localhost URL --> pw[Posit Workbench Extension]
pw -- external URL --> p
p -- external URL --> b[Browser] 
b -- HTTP request --> w[Posit Workbench]
w -- HTTP proxy --> hp
hp[Positron Help Proxy] --> hs
hs -- help content --> hp
hp -- help content --> w
w -- help content --> b
```

**Comment by jmcphers** [comment]
There's definitely some overlap here with the existing logic in the Posit Workbench extension, which already has logic for discovering localhost URLs and creating proxies for them. We could choose to re-use some of that code, or refactor that code to use the resolver APIs.

**Comment by sharon-wang** [comment]
## QA Notes

Please verify interactive plots, help content and the viewer in Positron Server Web and Positron on Workbench. Python app framework proxy support is WIP, logged as https://github.com/posit-dev/positron/issues/4769.

### Interactive Plots

#### Relevant PRs and issues
- https://github.com/posit-dev/positron/pull/4855
- https://github.com/posit-dev/positron/pull/4876
- https://github.com/posit-dev/positron/issues/4804

### Help Content

#### Relevant PRs and issues
- https://github.com/posit-dev/positron/pull/4814
- https://github.com/posit-dev/positron/pull/4837
- https://github.com/posit-dev/positron/issues/4847

### Viewer

#### Relevant PRs and issues
No specific PRs/issues for the Viewer. Proxying issues may have been fixed as part of the help proxy fixes.

#### Test case I used

A more complex case would be ideal!

1. Open https://github.com/posit-dev/qa-example-content/tree/main/workspaces/quarto_basic in Positron. Ensure quarto is already installed.
2. “Preview” the quarto_basic.qmd file so that the corresponding html and files are generated, and the html is previewed in the Viewer Pane.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.10.0-5
    OS Version          : OSX

### Test scenario(s) 

Quarto and shiny from qa-example-content look good!

Link(s) to TestRail test cases run or created:
