### ISSUE TITLE
Saving a new R notebook turns it into a Python notebook and starts Python

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4796]
#### Positron and OS details:

```
Positron Version: 2024.09.0 (Universal) build 77
Code - OSS Version: 1.93.0
Commit: 9b6f7c066546a4c7f104368fc769fb3768b08bfd
Date: 2024-09-23T02:43:50.589Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

#### Interpreter details:

R 4.2.3

## Describe the issue:

Saving a previously unsaved R notebook (.ipynb) file transforms it into a Python notebook.

## Steps to reproduce the issue:

1. Create a new R project
2. Create a new Jupyter notebook in the project (observe that the R kernel is selected)
3. Create and run some R code in the cells (works great)
4. Save the notebook and specify any filename when prompted

https://github.com/user-attachments/assets/64fd5e02-5134-47bb-bfd2-ede77e3f2de9

All the cells turn into Python cells, the notebook becomes a Python notebook, and Positron tries to start a Python interpreter.

## Expected or desired behavior:

The notebook should remain an R notebook even after being saved.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by seeM** [comment]
I am able to repro this. There have been a couple issues related to saving new notebooks and automatic kernel selection. It's a bit of a mess because of how generic the notebook-related code tries to be.

Related issues:

* https://github.com/posit-dev/positron/issues/2456
* https://github.com/posit-dev/positron/issues/2470
* https://github.com/posit-dev/positron/issues/2477
* https://github.com/posit-dev/positron/issues/2497

**Comment by midleman** [comment]
#### Verified Fixed
Positron Version(s) : [2024.11.0-49](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-49)
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed that when saving new notebook the kernel selection persists as expected.

### Link(s) to TestRail test cases run or created: 

n/a
