### ISSUE TITLE
Positron Web: Open... missing from Welcome page.

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4851]
#### Positron and OS details:

Main as of about 11am MST on 9/30

#### Interpreter details:

N/A

## Describe the issue:

Open...
or
Open Folder...

is missing on welcome page

<img width="262" alt="image" src="https://github.com/user-attachments/assets/3b153b28-3f8e-4f36-ae1b-23e4544a26e7">

## Steps to reproduce the issue:

Open welcome page and observe links under Open

## Expected or desired behavior:

A quick link to open a folder should be provided.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by timtmok** [comment]
We inherit this behaviour from VS Code. It uses `Open File...` instead of `Open...` for the web. We should decide whether web should be the same or keep this difference.

**Comment by timtmok** [comment]
https://github.com/posit-dev/positron/blob/91be0db898da1afca6873445b6c402806a77d881/src/vs/workbench/contrib/welcomeGettingStarted/common/gettingStartedContent.ts#L100-L125

**Comment by timtmok** [comment]
Mac is unique among the platforms as it is the only one that has a single action for opening both file and folder. Windows and Linux use dedicated actions for file and folder. From upstream, web only has open file for some reason. I can enable it so that it behaves like Windows and Linux.

This is what Windows looks like:
![Image](https://github.com/user-attachments/assets/81fcf458-2737-4591-b3b6-02f29f6798e0)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Main on 10/09/24 at 9:30 MST
    OS Version          : OSX

### Test scenario(s) 

Open Folder... is now present on the welcome screen!

Link(s) to TestRail test cases run or created:
