### ISSUE TITLE
Cursor Delay When Executing Code Line-by-Line Over SSH

### ISSUE THREAD

**Issue by ZHDATA2** [posit-dev/positron#5079]
## System details:
Device: MacBook with M1 chip
OS Version: macOS 15.01
Positron Version: 2024.11.0-49

## Describe the issue:
Hello,

I’ve encountered an issue while using the new IDE, when connected to a remote server via SSH. While executing code line-by-line, there is a noticeable delay where the cursor briefly pauses before jumping to the next line. This behavior only occurs when using the IDE over an SSH connection to a remote server.

When using the IDE locally, or when using RStudio Server in a similar remote setup, there is no such delay, and the code execution feels smooth. 

Has anyone else experienced this, or is there a workaround for this behavior?
## Steps to reproduce the issue:
	1.	Connect to a remote server via SSH.
	2.	Execute code line-by-line in either R or Python.
	3.	Notice the delay in cursor movement after each line execution.

## Expected or desired behavior:

Code should execute smoothly without a cursor delay when connected via SSH, similar to the experience in local execution or when using RStudio Server.

**Comment by jmcphers** [comment]
Could you provide some more info about your environment? 

- What's the network environment like between your local system and the remote system? (LAN? WAN? VPN?)
- What operating system and resources (CPU/RAM) are available on the remote system?
- Do you see this with R, Python, or both?

The line-by-line code execution feature calls into the remote host in order to analyze the code and figure out what region to execute. I'm guessing that call is taking a little longer in your environment due to network latency or an issue with the kernels on the remote host.

**Comment by juliasilge** [comment]
Let us know if you are able to share more details on your environment!
