### ISSUE TITLE
Add documentation for running interactive apps

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5122]
After our recent work on supporting the development experience for interactive apps (tracked in https://github.com/posit-dev/positron/issues/4558 and similar), we should add documentation for how folks can run apps. The Workbench docs will want to link to our Positron docs on the experience.

**Comment by AshleyHenry15** [comment]
Our[ VS Code Proxying Web Servers in the Workbench Extension](https://docs.posit.co/ide/server-pro/user/vs-code/guide/proxying-web-servers.html) section in the Workbench User Guide is fairly comprehensive.

I believe that Dash will be more built-in, but the FastAPI app differs from Workbench + VS Code because the Positron UX has a play button vs. having to start the app in the terminal.

I am unsure about Flask support but it seems that FastAPI would be the priority.

**Comment by sharon-wang** [comment]
Accidentally opened a duplicate issue #5216!

Copying over from there:

For Positron and Positron on Workbench users, it would be helpful if we documented a list of the supported frameworks and how to leverage the Run App functionality.

Supported Frameworks:
https://github.com/posit-dev/positron/blob/1cda237653eaad30a3edc45ff47d90bfa3fac24e/extensions/positron-python/src/client/positron/webAppCommands.ts#L17-L59

Any caveats like supported package versions, additional configuration, etc. could be called out on this page as well.

**Comment by sharon-wang** [comment]
## QA Notes

PR: https://github.com/posit-dev/positron-website/pull/16
New docs page: https://positron.posit.co/run-interactive-apps.html

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Current docs
    OS Version          : OSX

### Test scenario(s) 

Docs look great!

Link(s) to TestRail test cases run or created:
