### ISSUE TITLE
Show package information in code completion

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#5225]
#### Positron and OS details:

Positron Version: 2024.11.0 (system setup) build 116
Code - OSS Version: 1.93.0
Commit: 8b1688ababfa228db515a739050c466f3bb3089f
Date: 2024-10-28T02:47:45.218Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

#### Interpreter details:

R 4.3.2

## Describe the issue:
In Rstudio, when you call function, methods, it will show for you from where the method come from. It will be nice if we can have it in Positron

## Steps to reproduce the issue:

![Image](https://github.com/user-attachments/assets/394f13b4-3878-48f6-9ebf-049d657bf400)

![Image](https://github.com/user-attachments/assets/0f14d4cf-f8d4-4f1b-a83e-e5637798236a)

## Expected or desired behavior:
![Image](https://github.com/user-attachments/assets/bf67c9b9-c038-4a5d-844c-9b219dd393a5)

![Image](https://github.com/user-attachments/assets/c825e7df-6197-4ff7-8fe1-2502380821e7)

**Comment by lionel-** [comment]
I agree it's very useful to see the package in the completion list.

There are two relevant fields for `CompletionItem`:

- `detail`, which we currently use for displaying function parameters. This is the legacy field in the LSP spec. In the VSCode/Positron UI, it's hidden by default and only appears for the item currently selected.

- `label_details`, a newer field discussed in https://github.com/microsoft/vscode/issues/39441. It has two sub-fields `detail` and `description`. The former is meant for function parameters and is appended directly to the label without space (e.g. the label might be `mean` and `label_details.detail` would be `(x, ...)`. The `description` field is shown on the right. Both of these fields are always shown at all times for all items in the completion lists.

When `label_details` is supplied, `detail` is ignored. The server can provide both so that older clients that only understand `detail` still work as before.

So I think we have the following options.

- First, here is how things look like today:
   https://github.com/user-attachments/assets/98d03345-8a4f-4fd5-a78a-a1bbe8f5a456

- If we provide `label_details` with both fields we get a rather dense completion list. Also the package is ellipsised when the parameter list gets too large
   https://github.com/user-attachments/assets/ec13a0c9-f33b-42a7-825b-e2519c689503

- Since we have many other ways to get information about the parameter lists, in hover or in the completion doc, I suggest we only provide the package name:
   https://github.com/user-attachments/assets/206212a0-4f0f-4f25-b23e-b0b421cac8e0
   
   This last option is implemented in https://github.com/posit-dev/ark/pull/616

**Comment by ntluong95** [comment]
That's fast, thanks so much @lionel- I agree that the parameter list there is usually useless, so good to replace by the package source information. Much more useful

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-41](https://github.com/posit-dev/positron/releases/tag/2024.12.0-41)
OS Version(s) : Windows 11, Ubuntu 24

### Test scenario(s) 

Package info now shown in code completion

<img src="https://github.com/user-attachments/assets/ab6dca2d-839f-4a31-8b18-c896bf701208" width=50%>



### Link(s) to TestRail test cases run or created: 
N/A
