### ISSUE TITLE
Positron Workbench: Going back into a session starts new interpreter env

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#5267]
#### Positron and OS details:
Ubuntu 24
Positron [2024.11.0-140](https://github.com/posit-dev/positron/releases/tag/2024.11.0-140)
Workbench 2024.11.0-338.pro1

#### Interpreter details:

R 4.4.1
Python 3.10.10

## Describe the issue:

Going back into an existing Positron session starts a new interpreter environment.  This does not happen when just refreshing the tab, only when re-enter the session from Workbench launcher screen.

https://github.com/user-attachments/assets/497e55c6-8e69-4ce0-a1b7-b7af22a699c5

## Steps to reproduce the issue:

1. Start a new Positron Session
2. Start the R console & create a variable. eg. `x <-1`
3. Return to Workbench launcher screen and re-enter session

A new R env is created, losing old data.

## Expected or desired behavior:
The session would persist and the R data would still be present

Note.. the terminal pane seems to persist

**Comment by jmcphers** [comment]
- Do recent Workbench state changes fix this? (probably not but worth testing)
- Does this reproduce when a folder is open? (the no-folder state is a special case for workbench state)

**Comment by sharon-wang** [comment]
I built Workbench locally from `main` with the latest state changes and ran with `Positron 2024.11.1 build 4`.

> * Do recent Workbench state changes fix this? (probably not but worth testing)

Nope :( didn't fix this.

> * Does this reproduce when a folder is open? (the no-folder state is a special case for workbench state)

Yes, this issue still occurs when a folder is open.

---

If I copy the url of the Positron tab and paste the url in a new tab, the same issue occurs. So there's some state being lost or not getting reloaded properly when we open up an existing Positron session in a new tab.

Will be investigating further.

**Comment by jmcphers** [comment]
This is happening due to this code: 

https://github.com/posit-dev/positron/blob/909d8b64874b46195c29e97177c1b4b249a0d77a/src/vs/workbench/services/runtimeStartup/common/runtimeStartup.ts#L698-L704

It turns out that for Positron on Workbench, it is considered a "new window" whenever we reconnect (probably not a bug), so we're removing all the persisted R and Python sessions when we enter the codepath above, causing Positron to orphan the existing sessions and boot new ones. 

We _do_ need some variant of this behavior however! Without it, Positron tries to reconnect to old sessions if e.g. you end your Positron session and start a new one in the same workspace. That's a problem in both Desktop and Server spins of the system.

So the key problem is that we need to save the set of active R and Python sessions that persists within a Positron session but _not_ across Positron sessions in the same workspace. The underlying storage service doesn't have any session scope, so we may need to consult other sources or change the way these are read/written.

**Comment by jmcphers** [comment]
I took a look at how the Terminal tab handles this, since it solves an almost identical problem, and discovered (to my dismay) that ultimately it works by querying the PtyHost from the front end, e.g. here: 

https://github.com/posit-dev/positron/blob/909d8b64874b46195c29e97177c1b4b249a0d77a/src/vs/workbench/contrib/terminal/electron-sandbox/localTerminalBackend.ts#L369

We can't take this approach in Positron (as it stands) since we have insulated the supervisor from the front end too well -- there is no way for the front end to talk to it. 

Here are some possible ways around this problem:
- Stop trying to do *everything* in extension-land. Instead of having the supervisor run *under* the PtyHost, have it run alongside it, and allow Positron to query it directly, as it can the PtyHost. This feels the most complete as a solution, but would require a lot of additional infrastructure.
- Don't worry about persisting sessions too long; instead, provide a way to do a pre-flight check on a session to see if it's still running before we try to reconnect to it. At startup, check the persisted sessions before reconnecting to them. This is kind of gross, because it complicates startup even more, and it means we are going be recovering and cleaning up from stale data often, which smells bad from a design standpoint.
- Flip the script on session persistence: instead of having Positron maintain the list of sessions and ask the extensions to reconnect to them, have the extensions expose a way for Positron to ask them what is currently running. The supervisor extension can query the supervisor directly to get this list. 
- [Run away from home and live in the woods](https://www.wikihow.com/Run-Away-from-Home-and-Live-in-the-Woods)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-80](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-80)
Workbench Version(s):[2024.12.0+456.pro3](https://dailies.rstudio.com/version/2024.12.0+456.pro3)
OS Version(s) : Ubuntu 24

### Test scenario(s) 

* Start R & Python consoles
* Create a few variables
* Close tab
* Return to session

INterpreter session reconnected. Variables were still present, etc.

### Link(s) to TestRail test cases run or created:
