### ISSUE TITLE
Kallichore block by WithSecure Antivirus - Code security HEUR/APC

### ISSUE THREAD

**Issue by mburtin** [posit-dev/positron#5533]
#### Positron and OS details:

- Windows 11 Pro, 22631.4460

## Describe the issue:
My ogranization use a professionnal antivirus software : WithSecure 160.4. When I tried to install Positron in user mode, WithSecure detected a file as malicious and quarantined it. This file is "kcserver.exe", and the reason is : HEUR/APC.

## Steps to reproduce the issue:

1. Use WithSecure antivirus software
2. Try to install positron

## Expected or desired behavior:
No more false detections for HEUR/APC code. Unfortunately, in a professional environment, you don't necessarily have the option of bypassing and ignoring security software detections.

**Comment by jmcphers** [comment]
The HEUR code suggest that your antivirus engine is flagging `kcserver.exe` due to a heuristics rule -- that is, it didn't find a virus, but it thinks it kind of looks like one. This program can trip AV scanners because it makes network connections (to Positron) and it also starts other programs (R and Python kernels). It's harmless but looks suspicious.

Does your scanner report any additional detail about these codes, maybe in a log? If we don't know specifically what it's tripping on, there is not much hope we could address the issue.

Have you tried turning off the supervisor? You can do this in Settings; uncheck this option, then restart Positron:

![Image](https://github.com/user-attachments/assets/26c6d376-d0e0-4e42-89b6-8a3d4bd9adcd)

**Comment by mburtin** [comment]
Unfortunately I wasn't able to get more detailed information, except that it only concerns the User-Setup installer. I have reported the false positive to WithSecure. Personally, I have switched to a system installation and it works.

Thanks for the reply

**Comment by jmcphers** [comment]
OK, glad you're up and running!
